//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouNews.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SouNewsDBEntities : DbContext
    {
        public SouNewsDBEntities()
            : base("name=SouNewsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<LogOperate> LogOperate { get; set; }
        public virtual DbSet<Power> Power { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RolePower> RolePower { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
